import { z } from "zod";

const leadDispositionEnum = z.enum([
  "NEW", "ATTEMPTING_CONTACT", "CONTACTED", "INTERESTED", "APPOINTMENT_SET",
  "PRESENTED", "APPLICATION_SENT", "SOLD", "NOT_INTERESTED", "BAD_LEAD",
  "DNC", "RECYCLE", "FOLLOW_UP_LATER",
]);

const pipelineStageEnum = z.enum([
  "NEW_LEAD", "CONTACTING", "QUOTED", "APPOINTMENT_SET", "APPLICATION_STARTED",
  "UNDERWRITING", "APPROVED", "PLACED", "CHARGEBACK_RISK", "LOST",
]);

export const createLeadSchema = z.object({
  firstName: z.string().min(1, "First name is required"),
  lastName: z.string().min(1, "Last name is required"),
  fullName: z.string().optional(),
  phone: z.string().min(1, "Phone is required"),
  phone2: z.string().optional(),
  email: z.union([z.string().email(), z.literal("")]).optional(),
  source: z.string().optional(),
  vendor: z.string().optional(),
  campaign: z.string().optional(),
  subId: z.string().optional(),
  dateOfBirth: z.string().optional(),
  age: z.union([z.coerce.number(), z.literal("")]).optional(),
  gender: z.string().optional(),
  maritalStatus: z.string().optional(),
  address1: z.string().optional(),
  address2: z.string().optional(),
  address: z.string().optional(),
  city: z.string().optional(),
  state: z.string().optional(),
  zip: z.string().optional(),
  county: z.string().optional(),
  timeZone: z.string().optional(),
  preferredContactMethod: z.string().optional(),
  bestTimeToCall: z.string().optional(),
  leadType: z.string().optional(),
  leadFreshness: z.string().optional(),
  dateLeadReceived: z.string().optional(),
  spouseName: z.string().optional(),
  smokerStatus: z.string().optional(),
  beneficiaryRelation: z.string().optional(),
  beneficiaryPhone: z.string().optional(),
  emergencyContact: z.string().optional(),
  childrenYesNo: z.string().optional(),
  grandchildrenYesNo: z.string().optional(),
  decisionMakerNotes: z.string().optional(),
  coverageAmountInterest: z.union([z.coerce.number(), z.literal("")]).optional(),
  budgetMonthlyPremiumTarget: z.string().optional(),
  burialOrCremationPreference: z.string().optional(),
  existingLifeInsuranceYesNo: z.string().optional(),
  existingPolicyAmount: z.string().optional(),
  concernReasonForBuying: z.string().optional(),
  wantsFuneralPlanningHelpYesNo: z.string().optional(),
  preferredPaymentMode: z.string().optional(),
  height: z.string().optional(),
  weight: z.string().optional(),
  tobaccoStatus: z.string().optional(),
  prescriptionMedications: z.string().optional(),
  majorConditions: z.string().optional(),
  hospitalizationsLast2Years: z.string().optional(),
  cancerHistory: z.string().optional(),
  heartHistory: z.string().optional(),
  diabetes: z.string().optional(),
  copdOxygenUse: z.string().optional(),
  strokeHistory: z.string().optional(),
  kidneyDisease: z.string().optional(),
  mobilityIssues: z.string().optional(),
  mentalCapacityConcerns: z.string().optional(),
  nursingHomeAssistedLivingStatus: z.string().optional(),
  recentSurgeries: z.string().optional(),
  underwritingClassEstimatedEligibility: z.string().optional(),
  knockoutConditionYesNo: z.string().optional(),
  bankName: z.string().optional(),
  routingNumber: z.string().optional(),
  accountNumber: z.string().optional(),
  socialSecurityOrLast4: z.string().optional(),
  draftDate: z.string().optional(),
  incomeSource: z.string().optional(),
  beneficiaryPayorIfDifferent: z.string().optional(),
  paymentMethod: z.string().optional(),
  replacementInvolvedYesNo: z.string().optional(),
  carrierQuoted: z.string().optional(),
  planProduct: z.string().optional(),
  faceAmount: z.string().optional(),
  premium: z.string().optional(),
  applicationDate: z.string().optional(),
  applicationStatus: z.string().optional(),
  policyNumber: z.string().optional(),
  writingAgent: z.string().optional(),
  splitAgent: z.string().optional(),
  effectiveDate: z.string().optional(),
  approvalDate: z.string().optional(),
  declineReason: z.string().optional(),
  chargebackRisk: z.string().optional(),
  persistencyNotes: z.string().optional(),
  beneficiaryName: z.string().optional(),
  preferredLanguage: z.string().optional(),
  bestCallTime: z.string().optional(),
  leadCost: z.union([z.coerce.number(), z.literal("")]).optional(),
  leadScore: z.union([z.coerce.number(), z.literal("")]).optional(),
  consentStatus: z.string().optional(),
  doNotCall: z.boolean().optional(),
  assignedAgentId: z.string().optional(),
  assignedManagerId: z.string().optional(),
  disposition: leadDispositionEnum.optional(),
  pipelineStage: pipelineStageEnum.optional(),
  notes: z.string().optional(),
});

export const updateLeadSchema = createLeadSchema.partial().extend({
  fullName: z.string().optional(),
  lastContactedAt: z.string().datetime().optional(),
  nextFollowUpAt: z.string().datetime().optional(),
});

export const listLeadsQuerySchema = z.object({
  page: z.coerce.number().min(1).default(1),
  limit: z.coerce.number().min(1).max(100).default(20),
  search: z.string().optional(),
  disposition: leadDispositionEnum.optional(),
  pipelineStage: pipelineStageEnum.optional(),
  assignedAgentId: z.string().optional(),
  assignedManagerId: z.string().optional(),
  source: z.string().optional(),
  state: z.string().optional(),
  fromDate: z.string().optional(),
  toDate: z.string().optional(),
});

export type CreateLeadInput = z.infer<typeof createLeadSchema>;
export type UpdateLeadInput = z.infer<typeof updateLeadSchema>;
export type ListLeadsQuery = z.infer<typeof listLeadsQuerySchema>;
